### ISSUE TITLE
Update colour of banner

### ISSUE THREAD

**Issue by Lextuga007** [CDU-data-science-team/team-blog#16]
Change colour of banner to NHS branding colour - https://www.england.nhs.uk/nhsidentity/identity-guidelines/colours/

**Comment by ChrisBeeley** [comment]
We're using Trust branding, aren't we? Not NHS

**Comment by Lextuga007** [comment]
I checked Trust branding which led me to NHS branding. I've used some of the same colours, but not the 'blue' that is NHS and the Arial font is good practice for accessibility. I've not started any of these issues here but we can discuss it and use the Understanding Your Data pages as reference.

**Comment by ChrisBeeley** [comment]
I hate Arial, but I didn't know the link to accessibility. Shall we discuss in standup? Thanks
