### ISSUE TITLE
Change font to Arial

### ISSUE THREAD

**Issue by Lextuga007** [CDU-data-science-team/team-blog#17]
To comply with NHS branding and standards https://www.england.nhs.uk/nhsidentity/faq/do-we-have-to-use-fruitger-and-arial-fonts-for-everything/

**Comment by ChrisBeeley** [comment]
Ditto on this, we don't want to comply with NHS standards, do we? We want something more visually interesting.

(incidentally, this was a lot of issues. You may prefer to add tick boxes to one issue)

- [ ] One tick box
- [ ] Another thing to do
- [ ] One more
