### ISSUE TITLE
distill::create_post("Title of post") produces template with Zoë's details in

### ISSUE THREAD

**Issue by ChrisBeeley** [CDU-data-science-team/team-blog#45]
Not sure if this is a bug or a feature really but if you run `distill::create_post("Title of post")` it produces a post template with Zoë's details in (although the "ë" looks like "Ã«")

Is that what we want? Then we can just edit the template to be whoever is doing the post? Just checking 🙃

**Comment by Lextuga007** [comment]
That's very strange! It doesn't look like my name is in code that can be found through GitHub (looking for just Zo). The article template from nottshcMethods doesn't have a name https://github.com/CDU-data-science-team/nottshcMethods/blob/main/inst/rmarkdown/templates/distill/skeleton/skeleton.Rmd

Should we be using posts or articles? I get confused. Articles can be called using:

```
distill::create_article("Creating a post - SOP",
                        package = "nottshcMethods", 
                        template = "distill")
```

But what we really need is a post with a subfolder in /_posts/

**Comment by Lextuga007** [comment]
create_post(author = ) draws from the previous post automatically according to the documentation. I guess this is the difficulty with the blog site, we've been creating posts but the template is an article.
